version: '2'
services:
    odsupercomponent:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        volumes:
        - .:/opt/miniature.data
        command: "/opt/od4/bin/odsupercomponent --cid=150 --verbose=1 --configuration=/opt/miniature.data/configuration"

    proxy-miniature-pwm-motor:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        depends_on:
        - odsupercomponent
        network_mode: "host"
        restart: always
        privileged: true
        volumes:
        - /sys/:/sys/
        - /dev/:/dev/
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm-motor --cid=150 --freq=50 --id=1"

V2V:
image: car_controller/v2vcid
network_mode: "host"
restart: always
command: "opt/V2V.Service --cid=150 --cid2=151 --freq=5 --ip=172.20.10.9 --following=1 --leader=4 "

    # Your microservice.
    example:
        image: car_controller
        depends_on:
        - proxy-miniature-pwm-motor
        network_mode: "host"
        restart: always # maybe running only once is enough?
        command: "/opt/car_controller --cid=180 --freq=10"
